networks:
  pentest-net:
    external: true

services:
  vulnerable_app:
    build: .
    container_name: vulnerable_app
    networks: [pentest-net]
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=VulnerableDb2;User Id=sa;Password=SuperSecretPassword123!;TrustServerCertificate=True;"
