server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vulnerableapp
    static_configs:
      - targets:
          - localhost
        labels:
          job: vulnerableapp_logs
          __path__: /app/Logs/{log-*.txt,security-*.txt}
          category: Application
          environment: dev
    pipeline_stages:
      - match:
          selector: '{job="vulnerableapp_logs"} |~ "(?i)(Autenticación|Fallo de login|Intento de acceso|Logout)"'
          stages:
            - template:
                source: "category_sec"
                template: "Security"
            - template:
                source: "module_auth"
                template: "authentication"
            - labels:
                category: "category_sec"
                module: "module_auth"
      - match:
          selector: '{job="vulnerableapp_logs"} |~ "(?i)(AddComment|ApiController|Search|Usuario: )" !~ "(?i)(Autenticación|Fallo de login|Intento de acceso|Logout)"'
          stages:
            - template:
                source: "category_aud"
                template: "Audit"
            - labels:
                category: "category_aud"
      - match:
          selector: '{job="vulnerableapp_logs"} |~ "(?i)(order|pedido)"'
          stages:
            - template:
                source: "module_ord"
                template: "orders"
            - labels:
                module: "module_ord"
