server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vulnerableapp
    static_configs:
      - targets:
          - localhost
        labels:
          job: vulnerableapp_logs
          __path__: /app/Logs/*.txt
          tipo_registro: VulnerableApp # Label por defecto
          application: VulnerableApp

    pipeline_stages:
      # 1. Reglas para registros de Seguridad (Security)
      - match:
          selector: '{job="vulnerableapp_logs"} |~ "(?i)(Autenticación|Fallo de login|Intento de acceso|Logout|Contraseña|Password|Security|Unauthorized)"'
          stages:
            - template:
                source: log_category
                template: "Security"
            - labels:
                tipo_registro: log_category
                application: log_category

      # 2. Reglas para registros de Auditoría (Audit)
      - match:
          selector: '{job="vulnerableapp_logs"} |~ "(?i)(Agregado|Actualizado|Eliminado|Consultado|Modificado|Audit|ApiController|AddComment)"'
          stages:
            - template:
                source: log_category
                template: "Audit"
            - labels:
                tipo_registro: log_category
                application: log_category
