networks:
  pentest-net:
    external: true

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    networks: [pentest-net]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SuperSecretPassword123!"
